import abc
import aifc
import argparse
import array
import ast
import asynchat
import asyncio
import asyncore
import atexit
import audioop
import base64
import bdb
import binascii
import binhex
import bisect
import builtins
import bz2
import cProfile
import calendar
import cgi
import cgitb
import chunk
import cmath
import cmd
import code
import codecs
import codeop
import collections
import collections.abc
import colorsys
import compileall
import concurrent.futures
import configparser
import contextlib
import contextvars
import copy
import copyreg
import crypt
import csv
import ctypes
import curses
import curses.ascii
import curses.panel
import curses.textpad
import dataclasses
import datetime
import dbm
import dbm.dumb
import dbm.gnu
import dbm.ndbm
import decimal
import difflib
import dis
import doctest
import dummy_threading
import email
import email.charset
import email.contentmanager
import email.encoders
import email.errors
import email.generator
import email.header
import email.headerregistry
import email.iterators
import email.message
import email.mime
import email.parser
import email.policy
import email.utils
import encodings.idna
import encodings.utf_8_sig
import ensurepip
import enum
import errno
import faulthandler
import fcntl
import filecmp
import fileinput
import fnmatch
import formatter
import fractions
import ftplib
import functools
import gc
import getopt
import getpass
import gettext
import glob
import grp
import gzip
import hashlib
import heapq
import hmac
import html
import html.entities
import html.parser
import http
import http.client
import http.cookiejar
import http.cookies
import http.server
import imaplib
import imghdr
import imp
import importlib
import importlib.abc
import importlib.machinery
import importlib.resources
import importlib.util
import inspect
import io
import ipaddress
import itertools
import json
import json.tool
import keyword
import lib2to3
import linecache
import locale
import logging
import logging.config
import logging.handlers
import lzma
import macpath
import mailbox
import mailcap
import marshal
import math
import mimetypes
import mmap
import modulefinder
import multiprocessing
import multiprocessing.connection
import multiprocessing.dummy
import multiprocessing.managers
import multiprocessing.pool
import multiprocessing.sharedctypes
import netrc
import nis
import nntplib
import numbers
import operator
import optparse
import os
import os.path
import parser
import pathlib
import pdb
import pickle
import pickletools
import pipes
import pkgutil
import platform
import plistlib
import poplib
import posix
import pprint
import profile
import pstats
import pty
import pwd
import py_compile
import pyclbr
import pydoc
import queue
import quopri
import random
import re
import readline
import reprlib
import resource
import rlcompleter
import runpy
import sched
import secrets
import select
import selectors
import shelve
import shlex
import shutil
import signal
import site
import smtpd
import smtplib
import sndhdr
import socket
import socketserver
import sqlite3
import ssl
import stat
import statistics
import string
import stringprep
import struct
import subprocess
import sunau
import symbol
import symtable
import sys
import sysconfig
import syslog
import tabnanny
import tarfile
import telnetlib
import tempfile
import termios
import test
import test.support
import test.support.script_helper
import textwrap
import threading
import time
import timeit
import tkinter
import tkinter.scrolledtext
import tkinter.tix
import tkinter.ttk
import token
import tokenize
import trace
import traceback
import tracemalloc
import tty
import turtle
import turtledemo
import types
import typing
import unicodedata
import unittest
import unittest.mock
import urllib
import urllib.error
import urllib.parse
import urllib.request
import urllib.response
import urllib.robotparser
import uu
import uuid
import venv
import warnings
import wave
import weakref
import webbrowser
import wsgiref
import wsgiref.handlers
import wsgiref.headers
import wsgiref.simple_server
import wsgiref.util
import wsgiref.validate
import xdrlib
import xml
import xml.dom
import xml.dom.minidom
import xml.dom.pulldom
import xml.etree.ElementTree
import xml.parsers.expat
import xml.parsers.expat.errors
import xml.parsers.expat.model
import xml.sax
import xml.sax.handler
import xml.sax.saxutils
import xml.sax.xmlreader
import xmlrpc.client
import xmlrpc.server
import zipapp
import zipfile
import zipimport
import zlib

import requests
import zstd

exec(open(sys.argv[1]).read())
